package strings;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

class StringCollections {

    public static List<String> names() {
        List<String> result = new ArrayList<>();
        result.add("Alice");
        result.add("Bob");
        result.add("Bob");
        result.add("Arnold");
        result.add("Arnold");
        result.add("Barclay");
        result.add("Barnett");
        result.add("Barnett");
        result.add("Barnett");
        result.add("Coby");
        result.add("Cole");
        result.add("Clint");
        result.add("Diane");
        result.add("Darwin");
        result.add("Barnett");
        result.add("Coby");
        result.add("Cole");
        result.add("Clint");
        result.add("Diane");
        result.add("Darwin");
        result.add("Darwin");
        result.add("Ernest");
        result.add("Ernest");
        result.add("Franklin");
        result.add("Franklin");
        result.add("Gibson");
        result.add("Frank");
        result.add("Hilton");
        result.add("Hugh");
        result.add("Hugh");
        result.add("Jack");
        result.add("Julian");
        result.add("Lewis");
        result.add("Milton");
        result.add("Franklin");
        result.add("Franklin");
        result.add("Newton");
        result.add("Pascal");
        result.add("Patton");
        result.add("Patton");
        result.add("Patton");
        result.add("Radcliff");
        result.add("Ramsay");
        result.add("Swift");
        result.add("Swift");
        result.add("Tyson");
        result.add("Rob");
        result.add("Will");
        result.add("Will");
        Collections.shuffle(result);
        return result;
    }

    public static List<String> serials() {
        List<String> result = new ArrayList<>();
        result.add("Breaking Bad");
        result.add("Cosmos: A Space-Time Odyssey");
        result.add("Planet Earth");
        result.add("Game of Thrones");
        result.add("True Detective");
        result.add("The Wire");
        result.add("Sherlock");
        result.add("Cosmos");
        result.add("The Sopranos");
        result.add("Leyla ile Mecnun");
        result.add("Firefly");
        result.add("Arrested Development");
        result.add("I, Claudius");
        result.add("Avatar: The Last Airbender");
        result.add("Life");
        result.add("The Angry Video Game Nerd");
        result.add("Dexter");
        result.add("House of Cards");
        result.add("Batman: The Animated Series");
        result.add("Cowboy Bebop");
        result.add("Death Note");
        result.add("Freaks and Geeks");
        result.add("Friends");
        result.add("Rome");
        result.add("The Simpsons");
        result.add("Twin Peaks");
        result.add("Seinfeld");
        result.add("Monty Python's Flying Circus");
        result.add("Top Gear");
        result.add("Oz");
        result.add("House M.D.");
        result.add("Attack on Titan");
        result.add("Undercover");
        result.add("Twilight Zone");
        result.add("Blackadder Goes Forth");
        result.add("The Daily Show with Jon Stewart");
        result.add("Deadwood");
        result.add("Only Fools and Horses....");
        result.add("QI");
        result.add("Doctor Who");
        result.add("South Park");
        result.add("Fawlty Towers");
        result.add("Archer");
        result.add("Dragon Ball Z");
        result.add("It's Always Sunny in Philadelphia");
        result.add("Six Feet Under");
        result.add("Suits");
        result.add("Fullmetal Alchemist Brotherhood");
        result.add("The Office");
        result.add("One Piece");
        result.add("Isler G??ler");
        result.add("The Shield");
        result.add("Battlestar Galactica");
        result.add("Downton Abbey");
        result.add("Black-Adder II");
        result.add("The Adventures of Sherlock Holmes");
        result.add("Curb Your Enthusiasm");
        result.add("Black Adder the Third");
        result.add("The Thick of It");
        result.add("Chappelle's Show");
        result.add("Spaced");
        result.add("Berserk");
        result.add("The Prisoner");
        result.add("The West Wing");
        result.add("The X-Files");
        result.add("Flight of the Conchords");
        result.add("Supernatural");
        result.add("Whose Line Is It Anyway?");
        result.add("Sons of Anarchy");
        result.add("Boardwalk Empire");
        result.add("The Walking Dead");
        result.add("Justified");
        result.add("Futurama");
        result.add("Adventure Time");
        result.add("Spartacus: War of the Damned");
        result.add("Mystery Science Theater 3000");
        result.add("Mad Men");
        result.add("Behzat ?.: Bir Ankara Polisiyesi");
        result.add("The Legend of Korra");
        result.add("Fullmetal Alchemist");
        result.add("Dragonball");
        result.add("Father Ted");
        result.add("Black Mirror");
        result.add("The Colbert Report");
        result.add("The Originals");
        result.add("Friday Night Lights");
        result.add("Dragon Ball Z Kai");
        result.add("Dragon Ball");
        result.add("Star Trek: The Next Generation");
        result.add("Code Geass: Lelouch of the Rebellion");
        result.add("Peep Show");
        result.add("Shameless");
        result.add("Community");
        result.add("Modern Family");
        result.add("Homicide: Life on the Street");
        result.add("Jeeves and Wooster");
        result.add("The Big Bang Theory");
        result.add("Entourage");
        result.add("Louie");
        result.add("The Newsroom");
        result.add("Coupling");
        result.add("Garth Marenghi's Darkplace");
        result.add("Black Books");
        result.add("I'm Alan Partridge");
        result.add("Carnivale");
        result.add("Samurai Champloo");
        result.add("Luther");
        result.add("Agatha Christie's Poirot");
        result.add("The Muppet Show");
        result.add("How I Met Your Mother");
        result.add("The Venture Bros.");
        result.add("The Bugs Bunny Show");
        result.add("Summer Heights High");
        result.add("Lost");
        result.add("The IT Crowd");
        result.add("Prison Break");
        result.add("Naruto: Shippuden");
        result.add("Police Squad!");
        result.add("Neon Genesis Evangelion");
        result.add("Parks and Recreation");
        result.add("Mr. Bean");
        result.add("Terriers");
        result.add("Justice League");
        result.add("Red vs. Blue: The Blood Gulch Chronicles");
        result.add("Homeland");
        result.add("Young Justice");
        result.add("Scrubs");
        result.add("Vikings");
        result.add("The Bridge");
        result.add("Red Dwarf");
        result.add("Late Night with Conan O'Brien");
        result.add("MythBusters");
        result.add("Hellsing Ultimate");
        result.add("Ghost in the Shell: Stand Alone Complex");
        result.add("Rurouni Kenshin");
        result.add("X-Men");
        result.add("Fringe");
        result.add("Extras");
        result.add("24");
        result.add("I Love Lucy");
        result.add("Regular Show");
        result.add("Orange Is the New Black");
        result.add("Stargate SG-1");
        result.add("Hannibal");
        result.add("The Guild");
        result.add("FLCL");
        result.add("All in the Family");
        result.add("Boston Legal");
        result.add("M*A*S*H");
        result.add("Borgen");
        result.add("Trailer Park Boys");
        result.add("Psych");
        result.add("Californication");
        result.add("The Inbetweeners");
        result.add("Trigun");
        result.add("Family Guy");
        result.add("Foyle's War");
        result.add("American Horror Story");
        result.add("Misfits");
        result.add("The Avengers: Earth's Mightiest Heroes");
        result.add("Pushing Daisies");
        result.add("Blue Mountain State");
        result.add("Southland");
        result.add("Invader ZIM");
        result.add("The Adventures of Pete & Pete");
        result.add("Person of Interest");
        result.add("The League");
        result.add("Call the Midwife");
        result.add("My So-Called Life");
        result.add("Star Trek");
        result.add("Broadchurch");
        result.add("Life on Mars");
        result.add("Orphan Black");
        result.add("Veronica Mars");
        result.add("'Allo 'Allo!");
        result.add("The Wonder Years");
        result.add("The Mighty Boosh");
        result.add("Are You Afraid of the Dark?");
        result.add("Avrupa yakasi");
        result.add("Farscape");
        result.add("Rescue Me");
        result.add("Green Wing");
        result.add("Courage the Cowardly Dog");
        result.add("White Collar");
        result.add("Castle");
        result.add("The Boondocks");
        result.add("Almost Human");
        result.add("The Andy Griffith Show");
        result.add("Utopia");
        result.add("Get Smart");
        result.add("Party Down");
        result.add("The Adventures of Tintin");
        result.add("Metalocalypse");
        result.add("The Black Adder");
        result.add("Arrow");
        result.add("Ninjago: Masters of Spinjitzu");
        result.add("Robin of Sherwood");
        result.add("The Good Wife");

        return result;
    }
}
